{% set version = "2.0.3" %}

package:
  name: git-cliff
  version: {{ version }}

source:
  url: https://github.com/orhun/git-cliff/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f9ef0bcc33d91f3e3e4b511f81cc0b850da126486756dd84c8672b35ca545243

build:
  number: 0
  skip: true  # [not (osx and arm64)]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - pkg-config
    - cargo-bundle-licenses

  host:
    - libgit2

test:
  commands:
    - git-cliff --help

about:
  home: https://git-cliff.org
  summary: "A highly customizable changelog generator"
  description: "A highly customizable Changelog Generator that follows Conventional Commit specifications ⛰️"
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  doc_url: https://git-cliff.org/docs/
  dev_url: https://github.com/orhun/git-cliff

extra:
  recipe-maintainers:
    - orhun
