{% set version = "2.0.4" %}

package:
  name: git-cliff
  version: {{ version }}

source:
  url: https://github.com/orhun/git-cliff/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 49c26101ce1f834c1149fd7107e6cb774ea38410afe9cd5c8f35e0cdad417928

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - pkg-config
    - cargo-bundle-licenses
    - sysroot_linux-64 2.17  # [linux64]

  host:
    - libgit2
    # to build against libgit2 we also need the pkgconfig files
    # for zlib
    - zlib

test:
  commands:
    - git-cliff --help

about:
  home: https://git-cliff.org
  summary: "A highly customizable changelog generator"
  description: "A highly customizable Changelog Generator that follows Conventional Commit specifications ⛰️"
  license: MIT OR Apache-2.0
  license_file:
    - LICENSE-MIT
    - LICENSE-APACHE
    - THIRDPARTY.yml
  doc_url: https://git-cliff.org/docs/
  dev_url: https://github.com/orhun/git-cliff

extra:
  recipe-maintainers:
    - orhun
